name: 'Push to Master'
on:
  push:
    branches:
      - 'master'
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build-and-push-image:
    name: 'Build and Push Image'
    runs-on: [self-hosted, linux, normal]
    steps:
      - name: 'Check out code'
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0
      - name: 'Build Jammy docker image'
        uses: ./.github/actions/with-docker
        with:
          os: ubuntu
          distro: jammy
          image-tag: runtimeverificationinc/riscv-gnu-toolchain
      - name: 'Login to dockerhub'
        uses: docker/login-action@v2
        with:
          username: rvdockerhub
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: 'Push to dockerhub'
        run: |
          version=$(cat version)
          docker image push runtimeverificationinc/riscv-gnu-toolchain:ubuntu-jammy-${version}

  make-release:
    name: 'Update dependents'
    runs-on: ubuntu-latest
    needs: build-and-push-image
    steps:
      - name: 'Check out code'
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.push.head.sha }}
          fetch-depth: 0
      - name: 'Update dependents'
        run: |
          set -x
          VERSION=$(cat version)
          curl --fail                                                          \
            -X POST                                                            \
            -H "Accept: application/vnd.github+json"                           \
            -H "Authorization: Bearer ${{ secrets.JENKINS_GITHUB_PAT }}"       \
            -H "X-GitHub-Api-Version: 2022-11-28"                              \
            https://api.github.com/repos/runtimeverification/devops/dispatches \
            -d '{"event_type":"on-demand-test","client_payload":{"repo":"runtimeverification/riscv-gnu-toolchain-images","version":"'${VERSION}'"}}'
