name: 'Test PR'
on:
  pull_request:
    branches:
      - 'master'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-image:
    name: 'Build Image'
    runs-on: [self-hosted, linux, normal]
    steps:
      - name: 'Check out code'
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0
      - name: 'Build Jammy docker image'
        uses: ./.github/actions/with-docker
        with:
          os: ubuntu
          distro: jammy
          image-tag: runtimeverificationinc/riscv-gnu-toolchain
      - name: 'Smoke test'
        shell: bash {0}
        run: |
          toolchain_version=$(cat version)
          tag_name=riscv-gnu-toolchain:ubuntu-jammy-${toolchain_version}
          user=$(id -un)
          group=$(id -gn)
          docker run                                \
                 --name ${tag_name}                 \
                 --rm -it                           \
                 --detach                           \
                 --workdir /opt/workspace           \
                 --user ${user}:${group}            \
                 -v "$(pwd):/opt/workspace"         \
                 runtimeverificationinc/${tag_name}
          docker exec -t ${tag_name} /bin/bash -c ' \
                 cd test &&                         \
                 riscv64-unknown-elf-gcc -S hello.c -o hello.S.out && \
                 diff hello.S.out hello.S'
